### ISSUE TITLE
Jason field array look weird in done editing mode

### ISSUE THREAD

**Issue by jlachancekffein** [chasegiunta/craft-jason#21]
Sorry for create another issue, but we very like your plugin and use it a lot.

One problem we noticed is the display of the table in content editing mode.

For some unknown reason, some columns are wider than others, making editing complicated (this gives the impression that there are more levels of nesting) which is not the case.

On the next image, we see the problem on the line COLORFUL, DONOR and SURVIVOR.

![image](https://user-images.githubusercontent.com/24896469/59220299-a1599700-8b92-11e9-8524-7c6aea2855d6.png)

Is there a reason why columns are not equal even if there is room for more content?

Thank you for your support.

**Comment by chasegiunta** [comment]
@jlachancekffein The contents of each COLOR, DONOR, SURVIVOR are actually their own independent tables nested within those cells. The reason why all columns are not the same width is because for large datasets like the one you have above, forcing the column width to some arbitrary size could unnecessarily force wrapping when it's not needed in some places.

The columns are being sized based on how browsers decide to size the table column - they aren't being set explicitly anywhere.

As long as the table is full width, and not overflowing, it shouldn't give the impression that there is more levels of nesting.

**Comment by chasegiunta** [comment]
If you'd like to explicitly set the width, the best option might be to install the CPCSS plugin and style those nested table cells.

**Comment by jlachancekffein** [comment]
Thank you for your explanations.

We have changed the cell width via css and everything is now correctly displayed.

Thank you !

**Comment by jlachancekffein** [comment]
Thank you for your explanations.

We have changed the cell width via css and everything is now correctly displayed.

Thank you !
